# Generated by Django 3.0.4 on 2020-06-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notify',
            field=models.CharField(max_length=500),
        ),
    ]
